name: CodSpeed

on:
  push:
    branches:
      - develop
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # 3.12 is the minimum reqquired version for profiling enabled
          python-version: "3.12"

      - name: Install and configure Poetry
        run: |
          pip install -U pip poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: make build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest tests/benchmarks --codspeed
